name: First WorkFlow
on: workflow_dispatch
jobs: 
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: print hello
              run: echo "Hello world"
            - name: close connection
              run: echo "goodbye-conect"
            - name: multi line
              run: |
                echo "First output"
                echo "Second output"
